---
- name: Downloading Atom from github
  get_url:
    url: https://github.com/atom/atom/releases/download/v{{ atom_version }}/atom-amd64.deb
    dest: /tmp/

- name: Installing Atom
  apt:
    deb: /tmp/atom-amd64.deb
    force: 'yes'
